input {
  file {
    path => "/logs/cowrie/cowrie.json"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/cowrie.sincedb"
    codec => json
    add_field => { "trappot_source" => "cowrie" }
  }

  file {
    path => "/logs/zeek/conn.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/zeek-conn.sincedb"
    add_field => { "trappot_source" => "zeek_conn" }
  }

  file {
    path => "/logs/zeek/ssh.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/zeek-ssh.sincedb"
    add_field => { "trappot_source" => "zeek_ssh" }
  }
}

filter {
  if [message] =~ /^#/ {
    drop { }
  }

  if [trappot_source] == "cowrie" {
    date {
      match => [ "timestamp", "ISO8601" ]
    }
  }

  if [trappot_source] == "zeek_conn" {
    csv {
      separator => "	"
      columns => [
        "ts",
        "uid",
        "id.orig_h",
        "id.orig_p",
        "id.resp_h",
        "id.resp_p",
        "proto",
        "service",
        "duration",
        "orig_bytes",
        "resp_bytes",
        "conn_state",
        "local_orig",
        "local_resp",
        "missed_bytes",
        "history",
        "orig_pkts",
        "orig_ip_bytes",
        "resp_pkts",
        "resp_ip_bytes",
        "tunnel_parents"
      ]
    }

    date {
      match => [ "ts", "UNIX" ]
    }
  }

  if [trappot_source] == "zeek_ssh" {
    csv {
      separator => "	"
      columns => [
        "ts",
        "uid",
        "id.orig_h",
        "id.orig_p",
        "id.resp_h",
        "id.resp_p",
        "version",
        "auth_success",
        "auth_attempts",
        "direction",
        "client",
        "server",
        "cipher_alg",
        "mac_alg",
        "compression_alg",
        "kex_alg",
        "host_key_alg",
        "host_key",
        "remote_location.country_code",
        "remote_location.region",
        "remote_location.city",
        "remote_location.latitude",
        "remote_location.longitude"
      ]
    }

    date {
      match => [ "ts", "UNIX" ]
    }
  }
}

output {
  if [trappot_source] == "cowrie" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "trappot-cowrie"
    }
  } else if [trappot_source] == "zeek_conn" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "trappot-zeek-conn"
    }
  } else if [trappot_source] == "zeek_ssh" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "trappot-zeek-ssh"
    }
  }
}
